language: python
python:
 - 2.6
 - 2.7
env:
 - BEFORE_DJANGO_VERSION=1.5 TASTYPIE_VERSION="==0.9.12" MONGOENGINE_VERSION="==0.8.1"
 - BEFORE_DJANGO_VERSION=1.5 TASTYPIE_VERSION="==0.9.12" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"
 - BEFORE_DJANGO_VERSION=1.5 TASTYPIE_VERSION=">=0.9.12,<=0.10.0" MONGOENGINE_VERSION="==0.8.1"
 - BEFORE_DJANGO_VERSION=1.5 TASTYPIE_VERSION=">=0.9.12,<=0.10.0" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"
 - BEFORE_DJANGO_VERSION=1.6 TASTYPIE_VERSION="==0.9.12" MONGOENGINE_VERSION="==0.8.1"
 - BEFORE_DJANGO_VERSION=1.6 TASTYPIE_VERSION="==0.9.12" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"
 - BEFORE_DJANGO_VERSION=1.6 TASTYPIE_VERSION=">=0.9.12,<=0.10.0" MONGOENGINE_VERSION="==0.8.1"
 - BEFORE_DJANGO_VERSION=1.6 TASTYPIE_VERSION=">=0.9.12,<=0.10.0" MONGOENGINE_VERSION=">=0.8.1,<0.8.2"
services: mongodb
install:
 - pip install "Django<$BEFORE_DJANGO_VERSION"
 - pip install "django-tastypie$TASTYPIE_VERSION"
 - pip install "mongoengine$MONGOENGINE_VERSION"
 - pip install pep8 --use-mirrors
 - pip install pylint --use-mirrors
 - python setup.py install
before_script:
 - pep8 tastypie_mongoengine tests
 - pylint tastypie_mongoengine tests || true
script:
 - python -Wall setup.py test
